#!/bin/bash

# Get Software Version
# shellcheck disable=SC2155
export VERSION=$(cat VERSION)

# Build Image
docker build --build-arg VERSION="${VERSION}" -f "${DOCKERFILE_PATH}" -t "${IMAGE_NAME}" .
