#!/bin/bash

# Get Software Version
# shellcheck disable=SC2155
export VERSION=$(cat VERSION)

# Push Additional Version
docker tag "${IMAGE_NAME}" "${DOCKER_REPO}:${VERSION}"
docker push "${DOCKER_REPO}:${VERSION}"
