#!/bin/bash

# Get Software Version
# shellcheck disable=SC2155
export VERSION=$(cat VERSION)
SHORT_VERSION=$(echo "${VERSION}" | cut -d. -f1)

# Push Additional Version
docker tag "${IMAGE_NAME}" "${DOCKER_REPO}:${VERSION}"
docker tag "${IMAGE_NAME}" "${DOCKER_REPO}:${SHORT_VERSION}"
docker push "${DOCKER_REPO}:${VERSION}"
docker push "${DOCKER_REPO}:${SHORT_VERSION}"
