#!/bin/bash
# Generate The Environment File Used By The Project
# shellcheck disable=SC2154,SC2086

# A Function For Converting YAML Files To Bash Env Variables
parse_yaml() {
   local prefix=$2
   # shellcheck disable=SC2155
   local s='[[:space:]]*' w='[a-zA-Z0-9_\-]*' fs=$(echo @|tr @ '\034')
   sed -ne "s|^\($s\)\($w\)$s:$s\"\(.*\)\"$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
   awk -F$fs '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]}}
      if (length($3) > 0) {
         vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
         printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, $2, $3);
      }
   }'
}

# Load Variables From YAML Config File For Assignment
eval "$(parse_yaml ./project.yaml "project_")"
export project_project_hub_image
export project_project_hub_owner

cat << EOF > ./.env
# ---------------------------------------------------------------------------------------
# Generated by Project Setup Script - Don't Edit This Unless You Know What You Are Doing!
# ---------------------------------------------------------------------------------------

# Root Of Project Folder
PROJECT_ROOT_DIR=${PWD}

# Docker Variables For The Repository Name
DOCKER_REPO="${project_project_hub_owner}/${project_project_hub_image}"
DOCKER_LATEST_IMAGE="${project_project_hub_owner}/${project_project_hub_image}:latest"

EOF

# Output Project Specific Variables
./scripts/project_variables.sh
